# Generated by Django 6.0.1 on 2026-02-12 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('realisateur', models.CharField(max_length=200)),
                ('acteurs', models.TextField()),
                ('annee_sortie', models.IntegerField()),
                ('duree', models.IntegerField(help_text='Durée en minutes')),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='films/posters/')),
                ('video', models.FileField(blank=True, null=True, upload_to='films/videos/')),
                ('video_url', models.URLField(blank=True, help_text='Lien YouTube ou Vimeo', null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('est_populaire', models.BooleanField(default=False)),
                ('note', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.categorie')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='films.film')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
